---
# tasks file for redis

- name: Install Redis Package
  yum: name=redis state=latest

- name: Change bind from 127.0.0.1 to 0.0.0.0
  # command: sed -e 's/bind 127.0.0.1/bind 0.0.0.0/' -i /etc/redis.conf
  lineinfile: dest=/etc/redis.conf regexp='^bind ' line='bind 0.0.0.0' state=present
  tags:
    - rr
  notify:
    - restart redis